travis:
  secure:
    BINSTAR_TOKEN: 6yP6CfbKtqLQlhuLXLpYVvlju1PXpiQHiLJmHHejiRM47T96pYB0/DOTnrPDQQSmcNsX9VtTVKOusOpSAi4xMBcPQNDbN2zGcKra4SvDb6sAWh2w+X78DKy42X2tKhkqPr2LBwuWEKM6MxcrymVou/3E1FaTY/m/g3mdv5Ph/kTsUaDpnbAg592v8IWKDLQ9leJweG/AEsWyK0KhCMVj0xMi3RMsujAYFllMGJeib5BMQii78sci1DLRRZykN9CPI1OE5YFjoF55RMlPXDxuTOlvzMamUDoiavwMOcel3F61GL83MTCLwa9BcoYI8v6hc/qDU//IluwA+7Vx6sPw/w5Gu3z/U5ibz7+Uh4fy+rrn5dHOkCWHFPPdSrfyKP+iDXcLI2oB6FHyeSQt3zg5EpUyb/jhU9edX9u8f6FhZpl9yi1HJtzqDuDkz/NjirbAXNvYHo6f40oT44XP69t+HlEw9bd/PoS1q4g35hCcmRSpn8lbAOU75cuFVXBQScVLWkgojBT4U264HpLe1qQNRaZQWspPB/XlP3Hu+JUZl5KrHlC1Tjh2/GXO0GMiXPuDcXIZUUGHFBv5z8QSJ3G8IVM9+DhCp9eBeJJO2+5n3Fmso60OkY4SeCK5dhsXquGOo1ASCnAmRIu1fcyhlaxsuhz3zl8ojRfEG2bQ2sOhSLo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
